def write_obj(filename, vertices, faces):
    """
    Write mesh to OBJ file format.

    Parameters:
    -----------
    filename : str
        Output filename (should end in .obj)
    vertices : ndarray, shape(n, 3)
        Vertex positions
    faces : ndarray, shape (m, 3)
        Triangle faces as vertex indices
    """

    with open(filename, 'w') as f:
        # write header
        f.write('# OBJ file generated by topology_viz\n')
        f.write(f" # Vertices: {len(vertices)} \n")
        f.write(f" # Faces: {len(faces)}\n\n")

        # Write vertices
        for v in vertices:
            f.write(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")

        f.write("\n")

        # Write faces (.OBJ file format uses (1-based) indexing!)
        for face in faces:
            f.write(f"f {face[0]+1} {face[1]+1} {face[2]+1}\n")

    print(f"Wrote {len(vertices)} vertices and {len(faces)} faces to {filename}.")

